# SPDX-FileCopyrightText: 2026 zcbacxc
# SPDX-License-Identifier: AGPL-3.0-or-later

"""M4 coarse ResourceRef / execution-semantics contracts for the 16 built-ins.

Declarations are **static and advisory**. The runner still executes
linearly and does not interpret ``requires``, ``optional_inputs``,
``resource_capacity``, or ``concurrency_class``.

``reads`` / ``writes`` are qualified ResourceRefs (``ctx.*`` / ``meta.*`` /
``artifact.*`` / ``external.*``). Legacy ``inputs`` / ``outputs`` remain
coarse bare names in ``runner._BUILTIN_STEP_IO``; the gate maps them
through ``normalize_legacy_ref`` and checks the subset relation.

Audit honesty: these sets are AST-auditable *candidates*, not a
semantic/runtime proof of side effects (P4-3). Filesystem and provider
effects are documented separately; runtime observation is deferred to M5.
"""

from __future__ import annotations

from typing import Any, Dict

# Each entry supplies M4 kwargs for ``StepRegistry.register``.
# Omitted keys fall back to StepEntry conservative defaults
# (idempotent=False, concurrency_class="isolated_only",
#  requires=(), optional_inputs=(), failure_policy=None,
#  resource_capacity=None).
BUILTIN_STEP_CONTRACTS: Dict[str, Dict[str, Any]] = {
    "resolve_video": {
        "reads": (
            "ctx.movie_name",
            "ctx.library_dir",
            "meta.video_arg",
            "external.registry",
        ),
        "writes": ("ctx.source_video_path",),
        "idempotent": True,
        "concurrency_class": "safe",
        "requires": ("external.registry",),
    },
    "prepare_assets": {
        "reads": (
            "ctx.assets",
            "meta.bgm_request",
            "meta.bgm_ambient_path",
            "meta.bgm_metadata_path",
            "external.cache",
        ),
        "writes": ("ctx.assets",),
        "idempotent": True,
        "concurrency_class": "safe",
        "requires": ("external.cache",),
    },
    "research_plot": {
        "reads": (
            "ctx.movie_name",
            "meta.research_enabled",
            "meta.research_provider",
            "meta.lang",
            "external.llm",
            "external.research",
        ),
        "writes": (
            "ctx.research",
            "meta.movie_card",
            "meta.movie_card_source",
            "meta.tmdb_corrections",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": ("external.llm", "external.research"),
        "failure_policy": "degrade",  # matches soft=True
    },
    "generate_script": {
        "reads": (
            "ctx.research",
            "ctx.movie_name",
            "ctx.style",
            "ctx.duration",
            "meta.movie_card",
            "meta.lang",
            "meta.narration_lang",
            "meta.narrator_perspective",
            "meta.target_platform",
            "meta.focus_character",
            "meta.hook_templates",
            "external.llm",
        ),
        "writes": (
            "ctx.segments",
            "meta.script_source",
            "meta.script_degraded",
            "meta.beats_meta",
            "meta.set_pieces",
            "meta.script_qa",
            "meta.script_judge",
            "meta.script_phase",
            "meta.script_lang",
            "meta.script_target_count",
            "meta.script_beat_count",
            "meta.script_segment_count",
            "meta.script_truncated",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": ("external.llm",),
    },
    "export_script_md": {
        "reads": ("ctx.segments", "external.cache"),
        "writes": ("ctx.script_md_path",),
        "idempotent": True,
        "concurrency_class": "safe",
    },
    "generate_voice": {
        "reads": (
            "ctx.segments",
            "ctx.style",
            "meta.voice",
            "meta.lang",
            "meta.narration_lang",
            "meta.tts_provider",
            "meta.tts_style_prompt",
            "meta.tts_max_concurrent",
            "meta.tts_pause_ms",
            "external.tts",
            "external.cache",
        ),
        "writes": (
            "artifact.narration_audio",
            "ctx.timed_segments",
            "meta.duration_metrics",
            "meta.audio_quality",
            "meta.voice_used",
            "meta.tts_cache_stats",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": ("external.tts",),
    },
    "align_audio": {
        "reads": (
            "artifact.narration_audio",
            "ctx.timed_segments",
            "meta.lang",
            "meta.whisperx_model",
            "meta.whisperx_language",
            "meta.whisperx_device",
            "meta.embedding_model_name",
            "meta.funasr_model",
            "external.gpu",
        ),
        "writes": (
            "ctx.timed_segments",
            "meta.alignment_qa",
            "meta.align_degraded",
            "meta.align_backend_used",
            "meta.align_backend_reason",
            "meta.align_backend_attempted",
            "meta.align_backend",
            "meta.align_fallback",
            "meta.align_word_segments",
            "meta.align_words_assigned",
            "meta.align_word_tightened",
            "meta.align_segments",
            "meta.align_backward_skipped",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": (),
        "failure_policy": "degrade",  # matches soft=True
    },
    "detect_scenes": {
        "reads": (
            "ctx.source_video_path",
            "meta.scene_threshold",
            "meta.scene_frame_skip",
            "meta.scene_merge_min_duration",
            "external.moviepy",
            "external.ffmpeg",
        ),
        "writes": (
            "ctx.scenes",
            "meta.scene_detection_degraded",
        ),
        "idempotent": True,
        "concurrency_class": "isolated_only",
        "requires": ("external.ffmpeg",),
        "failure_policy": "degrade",
    },
    "match_clips": {
        "reads": (
            "ctx.timed_segments",
            "ctx.scenes",
            "ctx.source_video_path",
            "meta.lang",
            "meta.match_lang",
            "meta.match_text_source",
            "meta.match_min_score",
            "meta.match_topk",
            "meta.match_topk_reuse_penalty",
            "meta.match_speed_clamp_min",
            "meta.match_speed_clamp_max",
            "meta.match_drop_scene_min_duration",
            "meta.match_skip_intro_sec",
            "meta.match_drop_dark_luma",
            "meta.match_source_window",
            "meta.match_timeline_mode",
            "meta.match_act_weights",
            "meta.match_diversity_window",
            "meta.match_max_scene_reuse",
            "meta.match_transcript_cached",
            "meta.embedding_model_name",
            "meta.match_visual_features",
            "external.llm",
            "external.gpu",
        ),
        "writes": (
            "ctx.matched_clips",
            "meta.match_summary",
            "meta.match_quality",
            "meta.wp6_intro_dropped",
            "meta.wp6_dark_dropped",
            "meta.wp6_window_dropped",
            "meta.match_visual_features_available",
            "meta.match_visual_features_samples",
        ),
        "idempotent": True,
        "concurrency_class": "isolated_only",
        "requires": (),
        "failure_policy": "degrade",
    },
    "mix_bgm": {
        "reads": (
            "artifact.narration_audio",
            "ctx.assets",
            "meta.bgm_request",
            "meta.no_bgm",
            "meta.bgm_gain_db",
            "meta.bgm_duck_db",
            "meta.bgm_normalize",
            "meta.bgm_loudnorm",
            "meta.bgm_ambient_gain_db",
            "meta.bgm_ducking_backend",
            "meta.audio_target_dbfs",
            "external.ffmpeg",
        ),
        "writes": (
            "artifact.final_audio",
            "meta.bgm_transitions",
            "meta.bgm_selection",
            "meta.bgm_error",
            "meta.ambient_track",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": ("external.ffmpeg",),
        "failure_policy": "degrade",
    },
    "translate_subtitles": {
        "reads": (
            "ctx.timed_segments",
            "meta.subtitle_lang",
            "meta.source_lang",
            "meta.translate_provider",
            "meta.translate_retries",
            "meta.translate_chunk_chars",
            "meta.translate_chunk_size",
            "meta.translate_source_lang",
            "meta.translate_target_lang",
            "meta.lang",
            "external.llm",
        ),
        "writes": (
            "ctx.translated_texts",
            "meta.untranslated_indices",
            "meta.untranslated_count",
            "meta.translation_glossary",
        ),
        "idempotent": False,
        "concurrency_class": "isolated_only",
        "requires": ("external.llm",),
        "failure_policy": "degrade",
    },
    "generate_subtitle": {
        "reads": (
            "ctx.timed_segments",
            "ctx.translated_texts",
            "meta.subtitle_lang",
            "meta.subtitle_mode",
            "meta.subtitle_delivery",
            "meta.source_lang",
        ),
        "writes": (
            "artifact.subtitle",
            "ctx.subtitle_paths",
            "ctx.render_subtitle_path",
            "meta.subtitle_delivery_used",
            "meta.subtitle_mux_language",
            "meta.subtitle_delivery_fallback_reason",
        ),
        "idempotent": True,
        "concurrency_class": "safe",
    },
    "run_qa_gate": {
        "reads": (
            "meta.script_qa",
            "meta.audio_quality",
            "meta.subtitle_qa",
            "meta.alignment_qa",
            "meta.duration_metrics",
            "meta.match_summary",
            "meta.qa_enabled",
            "meta.qa_max_silence_db",
            "meta.qa_min_duration_ratio",
            "meta.qa_max_duration_ratio",
            "meta.qa_max_slideshow_risk",
            "meta.qa_max_black_ratio",
            "meta.qa_baseline_path",
        ),
        "writes": ("meta.qa_gate",),
        "idempotent": True,
        "concurrency_class": "safe",
        "failure_policy": "degrade",
    },
    "render_video": {
        "reads": (
            "ctx.matched_clips",
            "ctx.timed_segments",
            "ctx.scenes",
            "ctx.source_video_path",
            "ctx.assets",
            "artifact.final_audio",
            "ctx.render_subtitle_path",
            "meta.render_template",
            "meta.render_profile",
            "meta.render_encoder",
            "meta.render_video_codec",
            "meta.render_audio_codec",
            "meta.render_preset",
            "meta.render_crf",
            "meta.render_fps",
            "meta.render_threads",
            "meta.render_faststart",
            "meta.render_fit_mode",
            "meta.render_bg_color",
            "meta.render_output_name",
            "meta.render_cover_export",
            "meta.render_require_footage",
            "meta.render_min_footage_coverage",
            "meta.render_ffmpeg_timeout",
            "meta.render_preview_mode",
            "meta.render_preview_sec",
            "meta.render_title_card_sec",
            "meta.render_transition",
            "meta.render_transition_duration",
            "meta.render_text_animation",
            "meta.render_text_animation_duration",
            "meta.render_font_size",
            "meta.render_subtitle_position",
            "meta.render_subtitle_max_width_ratio",
            "meta.render_subtitle_bottom_margin_ratio",
            "meta.render_vertical_safe_area",
            "meta.render_bit_depth",
            "meta.render_color_space",
            "meta.aspect_ratio",
            "meta.video_format",
            "meta.distributed_render",
            "external.ffmpeg",
            "external.moviepy",
            "external.gpu",
        ),
        "writes": (
            "artifact.output_video",
            "meta.encoder_info",
            "meta.render_pixel",
            "meta.footage_coverage",
            "meta.footage_coverage_ratio",
            "meta.total_segments",
            "meta.usage",
        ),
        "idempotent": False,
        # Exclusive: a single render owns the encoder/GPU and writes the
        # primary output artifact. resource_capacity stays None (not
        # interpreted this phase).
        "concurrency_class": "exclusive",
        "requires": ("external.ffmpeg", "external.moviepy"),
    },
    "validate_deliverable": {
        "reads": (
            "artifact.output_video",
            "artifact.final_audio",
            "artifact.subtitle",
            "meta.qa_max_silence_db",
            "meta.qa_min_duration_ratio",
            "meta.qa_max_duration_ratio",
            "external.ffmpeg",
        ),
        "writes": (
            "meta.qa_report",
            "meta.video_qa",
            "meta.quality_dashboard",
        ),
        "idempotent": True,
        "concurrency_class": "safe",
        "requires": ("external.ffmpeg",),
    },
    "export_clips": {
        "reads": (
            "ctx.scenes",
            "ctx.matched_clips",
            "ctx.source_video_path",
            "meta.export_clips",
            "meta.no_clips",
            "external.ffmpeg",
        ),
        "writes": ("artifact.clips",),
        "idempotent": True,
        "concurrency_class": "isolated_only",
        "requires": ("external.ffmpeg",),
        "failure_policy": "degrade",
    },
}
