{{/* SPDX-FileCopyrightText: 2026 zcbacxc */}}
{{/* SPDX-License-Identifier: AGPL-3.0-or-later */}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "movie-narrator.serviceAccountName" . }}
  labels:
    {{- include "movie-narrator.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
# The app never talks to the Kubernetes API.
automountServiceAccountToken: false
{{- end }}
